# Generated by Django 4.2.7 on 2026-05-14 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='media_library/')),
                ('type', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitePopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='popups/')),
                ('style', models.CharField(choices=[('Info', 'Info'), ('Alert', 'Alert'), ('Announcement', 'Announcement')], default='Info', max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('show_once', models.BooleanField(default=True)),
                ('delay_seconds', models.IntegerField(default=0)),
                ('expires_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_contacted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='diploevent',
            name='attendees',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='diploevent',
            name='host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='diploevent',
            name='status',
            field=models.CharField(default='Upcoming', max_length=50),
        ),
        migrations.AddField(
            model_name='diploevent',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='date_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(blank=True, max_length=255)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.contact')),
            ],
        ),
        migrations.CreateModel(
            name='DiploTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(default='Medium', max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('related_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.contact')),
            ],
        ),
    ]
